### ISSUE TITLE
Implementing changing of bounty condition

### ISSUE THREAD

**Issue by EliteGreyIT67** [YuskaWu/one-piece-wanted-poster#2]
Bounty conditions files
![dead-or-alive](https://github.com/YuskaWu/one-piece-wanted-poster/assets/5107266/bbac6425-2dd9-482b-ae61-44258e2b191d)
![only-alive](https://github.com/YuskaWu/one-piece-wanted-poster/assets/5107266/79c26a94-b6d9-41c5-8646-2df96970ea8e)
![only-dead](https://github.com/YuskaWu/one-piece-wanted-poster/assets/5107266/6ae8cdba-7f7d-49c4-b106-5276a603bfeb)

**Comment by YuskaWu** [comment]
Well, that's a good idea, I'll consider implementing it once I have time.
